# Generated by Django 5.2.4 on 2025-08-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0003_remove_completed_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
