# Generated by Django 5.2.4 on 2025-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0004_remove_completed_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM ANDAMENTO', 'Em Andamento'), ('COMPLETADO', 'Concluído')], default='PENDENTE', max_length=20),
        ),
    ]
