# Generated by Django 5.2.4 on 2025-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_user_app', '0002_usuario_next_step_usuario_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Formatado'),
        ),
    ]
